// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Keyboard1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
