// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Screen1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea3 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea3, 312);
    lv_obj_set_height(ui_TextArea3, 49);
    lv_obj_set_x(ui_TextArea3, 0);
    lv_obj_set_y(ui_TextArea3, -60);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "请输入密码");
    lv_obj_set_style_text_font(ui_TextArea3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 800);
    lv_obj_set_height(ui_Keyboard1, 300);
    lv_obj_set_x(ui_Keyboard1, 12);
    lv_obj_set_y(ui_Keyboard1, -13);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_TextArea2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea2, 312);
    lv_obj_set_height(ui_TextArea2, 49);
    lv_obj_set_x(ui_TextArea2, 0);
    lv_obj_set_y(ui_TextArea2, -144);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "请输入账号");



    ui_login = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_login, 100);
    lv_obj_set_height(ui_login, 50);
    lv_obj_set_x(ui_login, 0);
    lv_obj_set_y(ui_login, 58);
    lv_obj_set_align(ui_login, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_login, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_login, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_login, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea9 = lv_textarea_create(ui_login);
    lv_obj_set_width(ui_TextArea9, 93);
    lv_obj_set_height(ui_TextArea9, 68);
    lv_obj_set_x(ui_TextArea9, -2);
    lv_obj_set_y(ui_TextArea9, 0);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea9, "确认");
    lv_obj_set_style_bg_color(ui_TextArea9, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea9, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_font(ui_TextArea9, &ui_font_Font1, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_login, ui_event_login, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
