// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton1 = lv_imagebutton_create(ui_Screen2);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_iconair_conditioner_png, NULL);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_ImgButton1, 104);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton1, -364);
    lv_obj_set_y(ui_ImgButton1, -194);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_Roller2 = lv_roller_create(ui_Screen2);
    lv_roller_set_options(ui_Roller2, "16°\n17°\n18°\n19°\n20°\n21°\n22°\n23°\n24°\n25°\n26°\n27°\n28°",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller2, lv_pct(11));
    lv_obj_set_height(ui_Roller2, lv_pct(19));
    lv_obj_set_x(ui_Roller2, 16);
    lv_obj_set_y(ui_Roller2, -196);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);

    ui_TextArea11 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea11, 194);
    lv_obj_set_height(ui_TextArea11, 70);
    lv_obj_set_x(ui_TextArea11, -154);
    lv_obj_set_y(ui_TextArea11, -194);
    lv_obj_set_align(ui_TextArea11, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea11, "目标温度:");
    lv_obj_set_style_text_font(ui_TextArea11, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea11, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TextArea11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea11, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



}
